### ISSUE TITLE
"missing mods.toml file" on mc 1.16.3 with forge 1.16.3 - 34.1.0

### ISSUE THREAD

**Issue by stdlo** [DNAlchemist/minecraft-skinny#7]
Might be me, using client and server versions 1.16.3 even though the version you listed on curse forge is 1.14.2.

Server forge version is `1.16.3 - 34.1.0`

This is the only mod I'm using and when I run it I get the following log output.
```
←[m←[33m[14:16:24] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file Mod File: C:\Users\█\Desktop\mcserver\Forge\mods\ssskins-0.0.4.jar is missing mods.toml file
←[m←[33m[14:16:24] [main/WARN] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: File C:\Users\█\Desktop\mcserver\Forge\mods\ssskins-0.0.4.jar has been ignored - it is invalid
```

It doesn't stop the server from working but it does not load skins from the config I gave it.

Here's my ./config/sskins.properties I've got a public github repo with some skins in there just for testing.
```
# ssskins.properties
ssskins-url=https://raw.githubusercontent.com/█/mcskins/main/
```

If you point me in the right direction idm making some changes and poking around when I get time.

**Comment by DNAlchemist** [comment]
I think the reason is src/main/resources/META-INF/mods.toml should be present in that Forge version.
Can you try to provide PR for that?
You can just run with `./gradlew build` or `gradlew.bat build` command to build jar file and test
https://mcforge.readthedocs.io/en/latest/gettingstarted/structuring/#the-modstoml-file
